#!/usr/bin/env python3
"""JSDA データの列マッピング定義"""

JSDA_COLUMNS = {
    0: {'name': 'trade_date', 'japanese_name': '売買日', 'description': '取引日（YYYYMMDD形式）', 'data_type': 'DATE'},
    1: {'name': 'bond_type', 'japanese_name': '銘柄区分', 'description': '債券の種類区分', 'data_type': 'INTEGER'},
    2: {'name': 'bond_code', 'japanese_name': '銘柄コード', 'description': '債券固有の識別コード', 'data_type': 'VARCHAR(50)'},
    3: {'name': 'bond_name', 'japanese_name': '銘柄名', 'description': '債券の正式名称', 'data_type': 'VARCHAR(200)'},
    4: {'name': 'maturity_date', 'japanese_name': '償還期限', 'description': '債券の満期日', 'data_type': 'DATE'},
    5: {'name': 'bid_price', 'japanese_name': '買気配値段', 'description': '買い手の提示価格', 'data_type': 'DECIMAL(10,3)'},
    6: {'name': 'ask_price', 'japanese_name': '売気配値段', 'description': '売り手の提示価格', 'data_type': 'DECIMAL(10,3)'},
    7: {'name': 'reference_price', 'japanese_name': '基準値段', 'description': '基準となる価格', 'data_type': 'DECIMAL(10,3)'},
    8: {'name': 'reference_yield', 'japanese_name': '基準利回り', 'description': '基準となる利回り', 'data_type': 'DECIMAL(8,3)'},
    9: {'name': 'price_change_mark', 'japanese_name': '前日比価格符号', 'description': '前日比の価格変動符号', 'data_type': 'VARCHAR(10)'},
    10: {'name': 'yield_change_mark', 'japanese_name': '前日比利回り符号', 'description': '前日比の利回り変動符号', 'data_type': 'VARCHAR(10)'},
    11: {'name': 'trading_status', 'japanese_name': '売買成立区分', 'description': '取引成立状況', 'data_type': 'INTEGER'},
    12: {'name': 'bid_volume', 'japanese_name': '買気配数量', 'description': '買い注文の数量', 'data_type': 'DECIMAL(15,1)'},
    13: {'name': 'ask_volume', 'japanese_name': '売気配数量', 'description': '売り注文の数量', 'data_type': 'DECIMAL(15,1)'},
    14: {'name': 'current_yield', 'japanese_name': '最終利回り', 'description': '最新の取引利回り', 'data_type': 'DECIMAL(8,3)'},
    15: {'name': 'time1_price', 'japanese_name': '時刻1価格', 'description': '特定時刻の価格', 'data_type': 'VARCHAR(20)'},
    16: {'name': 'time1_yield', 'japanese_name': '時刻1利回り', 'description': '特定時刻の利回り', 'data_type': 'VARCHAR(20)'},
    17: {'name': 'time2_price', 'japanese_name': '時刻2価格', 'description': '特定時刻の価格', 'data_type': 'VARCHAR(20)'},
    18: {'name': 'time2_yield', 'japanese_name': '時刻2利回り', 'description': '特定時刻の利回り', 'data_type': 'VARCHAR(20)'},
    19: {'name': 'reserved_field', 'japanese_name': '予約フィールド', 'description': '将来拡張用の予約領域', 'data_type': 'VARCHAR(10)'},
    20: {'name': 'market_sector', 'japanese_name': '市場区分', 'description': '取引市場の区分', 'data_type': 'INTEGER'},
    21: {'name': 'depth1_bid_price', 'japanese_name': '気配1買値段', 'description': '板情報の1番目買気配価格', 'data_type': 'VARCHAR(20)'},
    22: {'name': 'depth1_bid_yield', 'japanese_name': '気配1買利回り', 'description': '板情報の1番目買気配利回り', 'data_type': 'VARCHAR(20)'},
    23: {'name': 'depth2_bid_price', 'japanese_name': '気配2買値段', 'description': '板情報の2番目買気配価格', 'data_type': 'VARCHAR(20)'},
    24: {'name': 'depth2_bid_yield', 'japanese_name': '気配2買利回り', 'description': '板情報の2番目買気配利回り', 'data_type': 'VARCHAR(20)'},
    25: {'name': 'depth3_bid_price', 'japanese_name': '気配3買値段', 'description': '板情報の3番目買気配価格', 'data_type': 'VARCHAR(20)'},
    26: {'name': 'depth3_bid_yield', 'japanese_name': '気配3買利回り', 'description': '板情報の3番目買気配利回り', 'data_type': 'VARCHAR(20)'},
    27: {'name': 'depth1_ask_price', 'japanese_name': '気配1売値段', 'description': '板情報の1番目売気配価格', 'data_type': 'VARCHAR(20)'},
    28: {'name': 'depth1_ask_yield', 'japanese_name': '気配1売利回り', 'description': '板情報の1番目売気配利回り', 'data_type': 'VARCHAR(20)'},
}
